# Generated by Django 3.2.19 on 2023-06-10 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cohorte',
            name='number',
            field=models.IntegerField(default=9),
        ),
    ]
