# Generated by Django 3.2.19 on 2023-06-13 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_alter_attendance_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='document_type',
            field=models.CharField(choices=[('CC', 'Cédula Ciudadanía'), ('PPT', 'Permiso Protección Temporal'), ('CE', 'Cédula Extranjería'), ('TI', 'Tarjeta Identidad')], default='CC', max_length=3),
        ),
    ]
